Update deploywithvps.yaml

diff --git a/.github/workflows/deploywithvps.yaml b/.github/workflows/deploywithvps.yaml
--- a/.github/workflows/deploywithvps.yaml
+++ b/.github/workflows/deploywithvps.yaml
@@ -59,17 +59,18 @@ jobs:
               echo "No package.json found, skipping dependency installation."
             fi
 
-            # Setup environment variables for PM2
-            echo "Setting up environment variables..."
-            echo "PORT=3000" > .env
-
             # Start or restart the application using PM2
             if pm2 list | grep -q "$REPO_NAME"; then
               echo "Restarting PM2 process..."
-              pm2 restart "$REPO_NAME" --update-env
+              pm2 restart "$REPO_NAME" 
             else
+              echo "PM2 process not found, skipping to start PM2 step..."
+            fi
+
+            # Start PM2 process if not already running
+            if ! pm2 list | grep -q "$REPO_NAME"; then
               echo "Starting PM2 process..."
-              pm2 start npm --name "$REPO_NAME" -- start --env .env
+              pm2 start npm --name "$REPO_NAME" -- start
               pm2 save  # Save PM2 configuration to restart on reboot
             fi
 
