Update deploywithvps.yaml

diff --git a/.github/workflows/deploywithvps.yaml b/.github/workflows/deploywithvps.yaml
--- a/.github/workflows/deploywithvps.yaml
+++ b/.github/workflows/deploywithvps.yaml
@@ -64,14 +64,12 @@ jobs:
               echo "Restarting PM2 process..."
               pm2 restart "$REPO_NAME" --update-env
             else
-              echo "PM2 process not found, skipping to start PM2 step..."
+              echo "PM2 process not found, proceeding to start PM2 step..."
             fi
 
-            # Start PM2 process if not already running
-            if ! pm2 list | grep -q "$REPO_NAME"; then
-              echo "Starting PM2 process..."
-              pm2 start npm --name "$REPO_NAME" -- start
-              pm2 save  # Save PM2 configuration to restart on reboot
-            fi
+            # Start PM2 process
+            echo "Ensuring PM2 process is running..."
+            pm2 start npm --name "$REPO_NAME" -- start || echo "Failed to start PM2 process."
+            pm2 save  # Save PM2 configuration to restart on reboot
 
           EOF
